version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: bar_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: /wait-for-it.sh db:5432 -- python manage.py runserver
    volumes:
      - .:/app
      - C:/Users/juanv/OneDrive/Documentos/BAR2.0/frontend/templates:/app/templates
      - C:/Users/juanv/OneDrive/Documentos/BAR2.0/frontend/static:/app/static
    ports:
      - "5000:5000"
    depends_on:
      - db

  tests:
    build: .
    command: pytest
    volumes:
      - .:/app
      - C:/Users/juanv/OneDrive/Documentos/BAR2.0/frontend/templates:/app/templates
      - C:/Users/juanv/OneDrive/Documentos/BAR2.0/frontend/static:/app/static
    depends_on:
      - db

volumes:
  postgres_data:
